### ISSUE TITLE
The Goldfuscate plugin procedure blocks

### ISSUE THREAD

**Issue by LegoDeveloper1** [Goldorion/Goldfuscate#5]
In the Mcreate software, I tried using the 2 procedure blocks given, as shown in the picture posted in mcreate.net. It says "Selected global trigger is not supported by the selected generator. It will be ignored." And, "Selected global trigger requires obfuscate enabled in workspace settings, or the current generator does not support it." I was using forge 1.16.5. 
![Screenshot 2021-05-23 211337](https://user-images.githubusercontent.com/83732775/119283704-d6d6de00-bc0b-11eb-9bd4-2237a3cad46c.png)

**Comment by Goldorion** [comment]
The plugin doesn't support Forge 1.16.5 currently. When you see the selected global trigger or a procedure block is not supported by the current generator, it's not a bug. The developer of the plugin simply didn't add the support for this generator yet.

PS: This ticket is better than the previous one. ;)
