### ISSUE TITLE
Event needs to be registered in order to work; The plugin does not do this automatically

### ISSUE THREAD

**Issue by kleiders3010** [Goldorion/Goldfuscate#9]
![Screenshot_474](https://user-images.githubusercontent.com/71478358/159761504-b6cb19ed-9278-49a4-8595-7ad768c4dd36.png)
![Screenshot_473](https://user-images.githubusercontent.com/71478358/159761521-f74793e5-50c8-43c7-ae11-ee1f1fc9c82c.png)
After registering the event, the plugin finally works properly. 
Is there any way you could implement this into the plugin itself?

**Comment by kleiders3010** [comment]
https://user-images.githubusercontent.com/71478358/159761909-8482e43a-9931-4549-8c51-f3ac3543873c.mp4
![Screenshot_475](https://user-images.githubusercontent.com/71478358/159762052-005c511d-56d1-4da6-a623-eaef1d612c56.png)

Another example of the plugin working on mcreator (Changed the procedure a bit)

**Comment by Goldorion** [comment]
I don't have control over registering events. If MCreator doesn't register events in procedures, you have to report it to MCreator.

**Comment by kleiders3010** [comment]
Is this a core issue with mcreator not allowing plugins to modify the main mod class?
